# Generated by Django 5.0.2 on 2024-12-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('response', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
            ],
        ),
    ]
